######################################################################
# Automatically generated by qmake (2.01a) mer. oct. 15 21:45:28 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../shared

# Input
HEADERS += client.hpp \
../shared/protocole.hpp \
client_jeu.hpp \
client_debogage.hpp

SOURCES += main.cpp \
client.cpp \
../shared/protocole.cpp \
client_jeu.cpp\ 
client_debogage.cpp

QT += network
